#include "src/game/envfx_snow.h"

const GeoLayout monkat_switch_eyes_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 59, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(1, 0, 0, -37, -85, 1, 178),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(1, 0, 37, 4, -85, -1, -178),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, monkat_monkat_body_skinned_mat_override_third_eye_closed_0),
								GEO_TRANSLATE_ROTATE(1, 0, 28, 0, 3, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_body_mesh_mat_override_third_eye_closed_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, monkat_monkat_shoulders_skinned_mat_override_third_eye_closed_0),
										GEO_TRANSLATE_ROTATE(1, 0, 33, 0, -3, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_shoulders_mesh_mat_override_third_eye_closed_0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 8, 0, monkat_monkat_head_mesh_mat_override_third_eye_closed_0),
												GEO_TRANSLATE_ROTATE(1, 0, 8, 0, -45, 44, -174),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 26, -124, -51),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_arm_l_mesh_mat_override_third_eye_closed_0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(1, monkat_monkat_elbow_l_skinned_mat_override_third_eye_closed_0),
																GEO_TRANSLATE_ROTATE(1, 0, 13, 0, 0, 0, -2),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_elbow_l_mesh_mat_override_third_eye_closed_0),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(1, monkat_monkat_hand_l_skinned_mat_override_third_eye_closed_0),
																		GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 0, 0, 2),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_hand_l_mesh_mat_override_third_eye_closed_0),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(1, 0, 8, 0, -135, 125, 1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 45, -1, -37),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_arm_r_mesh_mat_override_third_eye_closed_0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(1, monkat_monkat_elbow_r_skinned_mat_override_third_eye_closed_0),
																GEO_TRANSLATE_ROTATE(1, 0, 13, 0, 0, 90, 2),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_elbow_r_mesh_mat_override_third_eye_closed_0),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(1, monkat_monkat_hand_r_skinned_mat_override_third_eye_closed_0),
																		GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 0, 0, -2),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_hand_r_mesh_mat_override_third_eye_closed_0),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(1, monkat_monkat_pants_center_skinned_mat_override_third_eye_closed_0),
								GEO_TRANSLATE_ROTATE(1, 0, -11, -1, 0, -90, -180),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_pants_center_mesh_mat_override_third_eye_closed_0),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 6, -8, 0, -90, 150),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_tail_mesh_mat_override_third_eye_closed_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, monkat_monkat_tail_low_skinned_mat_override_third_eye_closed_0),
										GEO_TRANSLATE_ROTATE(1, 0, 57, 0, 0, 0, -22),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_tail_low_mesh_mat_override_third_eye_closed_0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, monkat_monkat_tail_tip_skinned_mat_override_third_eye_closed_0),
												GEO_TRANSLATE_ROTATE(1, 0, 22, 0, 34, 90, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_tail_tip_mesh_mat_override_third_eye_closed_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(1, 9, -4, -1, -180, 90, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 0, 16, 0, monkat_monkat_leg_l_mesh_mat_override_third_eye_closed_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(1, monkat_monkat_foot_l_skinned_mat_override_third_eye_closed_0),
											GEO_TRANSLATE_ROTATE(1, 0, 36, 0, 0, 0, 74),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_foot_l_mesh_mat_override_third_eye_closed_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(1, -10, -4, -1, -180, 90, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 0, 17, 0, monkat_monkat_leg_r_mesh_mat_override_third_eye_closed_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(1, monkat_monkat_foot_r_skinned_mat_override_third_eye_closed_0),
											GEO_TRANSLATE_ROTATE(1, 0, 36, 0, 0, 180, -75),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_foot_r_mesh_mat_override_third_eye_closed_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout monkat_switch_eyes_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 59, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(1, 0, 0, -37, -85, 1, 178),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(1, 0, 37, 4, -85, -1, -178),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, monkat_monkat_body_skinned_mat_override_third_eye_closed_0),
								GEO_TRANSLATE_ROTATE(1, 0, 28, 0, 3, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_body_mesh_mat_override_third_eye_closed_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, monkat_monkat_shoulders_skinned_mat_override_third_eye_closed_0),
										GEO_TRANSLATE_ROTATE(1, 0, 33, 0, -3, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_shoulders_mesh_mat_override_third_eye_closed_0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 8, 0, monkat_monkat_head_mesh_mat_override_third_eye_closed_0),
												GEO_TRANSLATE_ROTATE(1, 0, 8, 0, -45, 44, -174),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 26, -124, -51),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_arm_l_mesh_mat_override_third_eye_closed_0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(1, monkat_monkat_elbow_l_skinned_mat_override_third_eye_closed_0),
																GEO_TRANSLATE_ROTATE(1, 0, 13, 0, 0, 0, -2),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_elbow_l_mesh_mat_override_third_eye_closed_0),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(1, monkat_monkat_hand_l_skinned_mat_override_third_eye_closed_0),
																		GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 0, 0, 2),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_hand_l_mesh_mat_override_third_eye_closed_0),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(1, 0, 8, 0, -135, 125, 1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 45, -1, -37),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_arm_r_mesh_mat_override_third_eye_closed_0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(1, monkat_monkat_elbow_r_skinned_mat_override_third_eye_closed_0),
																GEO_TRANSLATE_ROTATE(1, 0, 13, 0, 0, 90, 2),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_elbow_r_mesh_mat_override_third_eye_closed_0),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(1, monkat_monkat_hand_r_skinned_mat_override_third_eye_closed_0),
																		GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 0, 0, -2),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_hand_r_mesh_mat_override_third_eye_closed_0),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(1, monkat_monkat_pants_center_skinned_mat_override_third_eye_closed_0),
								GEO_TRANSLATE_ROTATE(1, 0, -11, -1, 0, -90, -180),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_pants_center_mesh_mat_override_third_eye_closed_0),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 6, -8, 0, -90, 150),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_tail_mesh_mat_override_third_eye_closed_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, monkat_monkat_tail_low_skinned_mat_override_third_eye_closed_0),
										GEO_TRANSLATE_ROTATE(1, 0, 57, 0, 0, 0, -22),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_tail_low_mesh_mat_override_third_eye_closed_0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, monkat_monkat_tail_tip_skinned_mat_override_third_eye_closed_0),
												GEO_TRANSLATE_ROTATE(1, 0, 22, 0, 34, 90, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_tail_tip_mesh_mat_override_third_eye_closed_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(1, 9, -4, -1, -180, 90, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 0, 16, 0, monkat_monkat_leg_l_mesh_mat_override_third_eye_closed_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(1, monkat_monkat_foot_l_skinned_mat_override_third_eye_closed_0),
											GEO_TRANSLATE_ROTATE(1, 0, 36, 0, 0, 0, 74),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_foot_l_mesh_mat_override_third_eye_closed_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(1, -10, -4, -1, -180, 90, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 0, 17, 0, monkat_monkat_leg_r_mesh_mat_override_third_eye_closed_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(1, monkat_monkat_foot_r_skinned_mat_override_third_eye_closed_0),
											GEO_TRANSLATE_ROTATE(1, 0, 36, 0, 0, 180, -75),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_foot_r_mesh_mat_override_third_eye_closed_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout monkat_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(1000),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 135, 65),
			GEO_OPEN_NODE(),
				GEO_SCALE(0, 78643),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 59, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_TRANSLATE_ROTATE(1, 0, 0, -37, -85, 1, 178),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(1, 0, 37, 4, -85, -1, -178),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(1, monkat_monkat_body_skinned),
														GEO_TRANSLATE_ROTATE(1, 0, 28, 0, 3, 0, 0),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_body_mesh),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(1, monkat_monkat_shoulders_skinned),
																GEO_TRANSLATE_ROTATE(1, 0, 33, 0, -3, 0, 0),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_shoulders_mesh),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(1, 0, 8, 0, monkat_monkat_head_mesh),
																		GEO_TRANSLATE_ROTATE(1, 0, 8, 0, -45, 44, -174),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
																			GEO_OPEN_NODE(),
																				GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 26, -124, -51),
																				GEO_OPEN_NODE(),
																					GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_arm_l_mesh),
																					GEO_OPEN_NODE(),
																						GEO_DISPLAY_LIST(1, monkat_monkat_elbow_l_skinned),
																						GEO_TRANSLATE_ROTATE(1, 0, 13, 0, 0, 0, -2),
																						GEO_OPEN_NODE(),
																							GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_elbow_l_mesh),
																							GEO_OPEN_NODE(),
																								GEO_DISPLAY_LIST(1, monkat_monkat_hand_l_skinned),
																								GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 0, 0, 2),
																								GEO_OPEN_NODE(),
																									GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_hand_l_mesh),
																								GEO_CLOSE_NODE(),
																							GEO_CLOSE_NODE(),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																		GEO_TRANSLATE_ROTATE(1, 0, 8, 0, -135, 125, 1),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
																			GEO_OPEN_NODE(),
																				GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 45, -1, -37),
																				GEO_OPEN_NODE(),
																					GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_arm_r_mesh),
																					GEO_OPEN_NODE(),
																						GEO_DISPLAY_LIST(1, monkat_monkat_elbow_r_skinned),
																						GEO_TRANSLATE_ROTATE(1, 0, 13, 0, 0, 90, 2),
																						GEO_OPEN_NODE(),
																							GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_elbow_r_mesh),
																							GEO_OPEN_NODE(),
																								GEO_DISPLAY_LIST(1, monkat_monkat_hand_r_skinned),
																								GEO_TRANSLATE_ROTATE(1, 0, 20, 0, 0, 0, -2),
																								GEO_OPEN_NODE(),
																									GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_hand_r_mesh),
																								GEO_CLOSE_NODE(),
																							GEO_CLOSE_NODE(),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_DISPLAY_LIST(1, monkat_monkat_pants_center_skinned),
														GEO_TRANSLATE_ROTATE(1, 0, -11, -1, 0, -90, -180),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_pants_center_mesh),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(1, 0, 6, -8, 0, -90, 150),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_tail_mesh),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(1, monkat_monkat_tail_low_skinned),
																GEO_TRANSLATE_ROTATE(1, 0, 57, 0, 0, 0, -22),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_tail_low_mesh),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(1, monkat_monkat_tail_tip_skinned),
																		GEO_TRANSLATE_ROTATE(1, 0, 22, 0, 34, 90, 0),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_tail_tip_mesh),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(1, 9, -4, -1, -180, 90, 0),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(1, 0, 16, 0, monkat_monkat_leg_l_mesh),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(1, monkat_monkat_foot_l_skinned),
																	GEO_TRANSLATE_ROTATE(1, 0, 36, 0, 0, 0, 74),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_foot_l_mesh),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(1, -10, -4, -1, -180, 90, 0),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(1, 0, 17, 0, monkat_monkat_leg_r_mesh),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(1, monkat_monkat_foot_r_skinned),
																	GEO_TRANSLATE_ROTATE(1, 0, 36, 0, 0, 180, -75),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(1, 0, 0, 0, monkat_monkat_foot_r_mesh),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, monkat_switch_eyes_opt1),
							GEO_BRANCH(1, monkat_switch_eyes_opt2),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, monkat_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, monkat_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, monkat_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, monkat_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, monkat_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, monkat_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, monkat_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, monkat_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
