const GeoLayout bowser_1_area_1_CaveLevel[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, -1875, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 4071, bowser_1_CaveGeo_mesh),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, -1875, bowser_1_deathPlane_mesh),
					GEO_ANIMATED_PART(1, 0, 0, -2196, bowser_1_instawarp_mesh),
					GEO_ANIMATED_PART(1, -490, -373, -1067, bowser_1_Logs_mesh),
					GEO_ANIMATED_PART(1, 0, 0, -2196, bowser_1_Pillars_mesh),
					GEO_ANIMATED_PART(5, 0, 0, -1875, bowser_1_Water_mesh),
					GEO_ANIMATED_PART(5, 0, 0, -1875, bowser_1_Waterfalls_mesh),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_1_area_1_level[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(80.0000, 100, 25000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(14, 0, 0, -1875, 0, -213, -1875, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bowser_1_area_1_CaveLevel),
					GEO_RENDER_OBJ(),
					GEO_ASM(0, geo_enfvx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, bowser_1_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, bowser_1_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, bowser_1_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, bowser_1_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, bowser_1_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, bowser_1_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, bowser_1_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, bowser_1_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
