extern const GeoLayout bowser_1_area_1_geo[];
extern const GeoLayout bowser_1_dl_1entrySlide_geo[];
extern const GeoLayout bowser_1_dl_2firstRoom_geo[];
extern const GeoLayout bowser_1_dl_4MainRoom_geo[];
extern const GeoLayout bowser_1_area_1[];
extern const Collision bowser_1_area_1_collision[];
extern const u8 bowser_1_area_1_collision_rooms[];
extern const MacroObject bowser_1_area_1_CaveLevelArea_macro_objs[];
extern const GeoLayout bowser_1_area_2_geo[];
extern const GeoLayout bowser_1_area_2[];
extern const Collision bowser_1_area_2_collision[];
extern const MacroObject bowser_1_area_2_CaveLevelArea2_macro_objs[];
extern Vtx bowser_1_dl_slideGeo_mesh_vtx_0[109];
extern Gfx bowser_1_dl_slideGeo_mesh_tri_0[];
extern Vtx bowser_1_dl_slideWater_mesh_vtx_0[24];
extern Gfx bowser_1_dl_slideWater_mesh_tri_0[];
extern Vtx bowser_1_dl_CaveGeo_001_mesh_vtx_0[24];
extern Gfx bowser_1_dl_CaveGeo_001_mesh_tri_0[];
extern Vtx bowser_1_dl_Logs_mesh_vtx_0[62];
extern Gfx bowser_1_dl_Logs_mesh_tri_0[];
extern Vtx bowser_1_dl_WaterCenter_mesh_vtx_0[25];
extern Gfx bowser_1_dl_WaterCenter_mesh_tri_0[];
extern Vtx bowser_1_dl_WaterFallRoomGeo_mesh_vtx_0[30];
extern Gfx bowser_1_dl_WaterFallRoomGeo_mesh_tri_0[];
extern Vtx bowser_1_dl_WaterFallRoomGeo_mesh_vtx_1[90];
extern Gfx bowser_1_dl_WaterFallRoomGeo_mesh_tri_1[];
extern Vtx bowser_1_dl_WaterFallRoomGeo_mesh_vtx_2[44];
extern Gfx bowser_1_dl_WaterFallRoomGeo_mesh_tri_2[];
extern Vtx bowser_1_dl_WaterFallRoomGeo_mesh_vtx_3[91];
extern Gfx bowser_1_dl_WaterFallRoomGeo_mesh_tri_3[];
extern Vtx bowser_1_dl_firstRoomGeo_mesh_vtx_0[129];
extern Gfx bowser_1_dl_firstRoomGeo_mesh_tri_0[];
extern Vtx bowser_1_dl_firstRoomWater_mesh_vtx_0[6];
extern Gfx bowser_1_dl_firstRoomWater_mesh_tri_0[];
extern Vtx bowser_1_dl_stalags_mesh_vtx_0[14];
extern Gfx bowser_1_dl_stalags_mesh_tri_0[];
extern Vtx bowser_1_dl_stalags_mesh_vtx_1[14];
extern Gfx bowser_1_dl_stalags_mesh_tri_1[];
extern Vtx bowser_1_dl_stalags_mesh_vtx_2[20];
extern Gfx bowser_1_dl_stalags_mesh_tri_2[];
extern Vtx bowser_1_dl_waterFallRoomWaterfalls_mesh_vtx_0[42];
extern Gfx bowser_1_dl_waterFallRoomWaterfalls_mesh_tri_0[];
extern Vtx bowser_1_dl_CaveGeo_mesh_vtx_0[280];
extern Gfx bowser_1_dl_CaveGeo_mesh_tri_0[];
extern Vtx bowser_1_dl_CaveGeo_mesh_vtx_1[24];
extern Gfx bowser_1_dl_CaveGeo_mesh_tri_1[];
extern Vtx bowser_1_dl_Pillars_mesh_vtx_0[309];
extern Gfx bowser_1_dl_Pillars_mesh_tri_0[];
extern Vtx bowser_1_dl_Water_mesh_vtx_0[14];
extern Gfx bowser_1_dl_Water_mesh_tri_0[];
extern Vtx bowser_1_dl_cultPathextension_mesh_vtx_0[88];
extern Gfx bowser_1_dl_cultPathextension_mesh_tri_0[];
extern Vtx bowser_1_dl_cultPathextension_mesh_vtx_1[4];
extern Gfx bowser_1_dl_cultPathextension_mesh_tri_1[];
extern Vtx bowser_1_dl_deathPlane_mesh_vtx_0[9];
extern Gfx bowser_1_dl_deathPlane_mesh_tri_0[];
extern Vtx bowser_1_dl_deathPlane_001_mesh_vtx_0[9];
extern Gfx bowser_1_dl_deathPlane_001_mesh_tri_0[];
extern Vtx bowser_1_dl_instawarp_mesh_vtx_0[7];
extern Gfx bowser_1_dl_instawarp_mesh_tri_0[];
extern Vtx bowser_1_dl_CultRoom_mesh_vtx_0[4];
extern Gfx bowser_1_dl_CultRoom_mesh_tri_0[];
extern Vtx bowser_1_dl_CultRoom_mesh_vtx_1[183];
extern Gfx bowser_1_dl_CultRoom_mesh_tri_1[];
extern Vtx bowser_1_dl_CultRoom_mesh_vtx_2[32];
extern Gfx bowser_1_dl_CultRoom_mesh_tri_2[];
extern Vtx bowser_1_dl_Logs_001_mesh_vtx_0[160];
extern Gfx bowser_1_dl_Logs_001_mesh_tri_0[];

extern Gfx bowser_1_dl_slideGeo_mesh[];
extern Gfx bowser_1_dl_slideWater_mesh[];
extern Gfx bowser_1_dl_CaveGeo_001_mesh[];
extern Gfx bowser_1_dl_Logs_mesh[];
extern Gfx bowser_1_dl_WaterCenter_mesh[];
extern Gfx bowser_1_dl_WaterFallRoomGeo_mesh[];
extern Gfx bowser_1_dl_firstRoomGeo_mesh[];
extern Gfx bowser_1_dl_firstRoomWater_mesh[];
extern Gfx bowser_1_dl_stalags_mesh[];
extern Gfx bowser_1_dl_waterFallRoomWaterfalls_mesh[];
extern Gfx bowser_1_dl_CaveGeo_mesh[];
extern Gfx bowser_1_dl_Pillars_mesh[];
extern Gfx bowser_1_dl_Water_mesh[];
extern Gfx bowser_1_dl_cultPathextension_mesh[];
extern Gfx bowser_1_dl_deathPlane_mesh[];
extern Gfx bowser_1_dl_deathPlane_001_mesh[];
extern Gfx bowser_1_dl_instawarp_mesh[];
extern Gfx bowser_1_dl_CultRoom_mesh[];
extern Gfx bowser_1_dl_Logs_001_mesh[];
extern Gfx bowser_1_dl_material_revert_render_settings[];

