// 0x0D000114
const GeoLayout toad_geo_000114[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 145, -20, 0, NULL),
            GEO_SCALE(LAYER_OPAQUE, 0xee00),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 285, -70, 0, toad_toadle_head_mesh),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, -10, toad_toadle_vest_mesh),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 8, 0, toad_toadle_body_mesh),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 4, 15, 38, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 9, -25, 3, toad_toadle_foot_l_mesh),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 4, 15, -38, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 9, -25, -3, toad_toadle_foot_r_mesh),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 15, 55, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 17, 0, 4, toad_toadle_arm_l_mesh),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 15, -55, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 17, 0, -4, toad_toadle_arm_r_mesh),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_RETURN(),
};

// 0x0D00027C
const GeoLayout toad_geo_00027C[] = {
   GEO_NODE_START(),
//    GEO_OPEN_NODE(),
//       GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
//       GEO_OPEN_NODE(),
//          GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
//          GEO_OPEN_NODE(),
//             GEO_ANIMATED_PART(LAYER_TRANSPARENT, 145, -20, 0, NULL),
//             GEO_SCALE(LAYER_TRANSPARENT, 0xee00),
//             GEO_OPEN_NODE(),
// #ifdef VERSION_JP
//                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 285, -70, 0, toad_seg6_dl_06007710),
// #else
//                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 285, -70, 0, toad_toadle_head_mesh),
// #endif
//             GEO_CLOSE_NODE(),
// #ifdef VERSION_JP
//             GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, -10, toad_seg6_dl_06007A48),
// #else
//             GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, -10, toad_toadle_body_mesh),
// #endif
//             GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 8, 0, toad_toadle_vest_mesh),
//             GEO_ANIMATED_PART(LAYER_TRANSPARENT, 4, 15, 38, NULL),
//             GEO_OPEN_NODE(),
//                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
//                GEO_OPEN_NODE(),
//                   GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, NULL),
//                   GEO_OPEN_NODE(),
//                      GEO_ANIMATED_PART(LAYER_TRANSPARENT, 9, -25, 3, toad_toadle_arm_l_mesh),
//                   GEO_CLOSE_NODE(),
//                GEO_CLOSE_NODE(),
//             GEO_CLOSE_NODE(),
//             GEO_ANIMATED_PART(LAYER_TRANSPARENT, 4, 15, -38, NULL),
//             GEO_OPEN_NODE(),
//                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
//                GEO_OPEN_NODE(),
//                   GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, NULL),
//                   GEO_OPEN_NODE(),
//                      GEO_ANIMATED_PART(LAYER_TRANSPARENT, 9, -25, -3, toad_toadle_arm_l_mesh),
//                   GEO_CLOSE_NODE(),
//                GEO_CLOSE_NODE(),
//             GEO_CLOSE_NODE(),
//             GEO_ANIMATED_PART(LAYER_TRANSPARENT, 110, 15, 55, NULL),
//             GEO_OPEN_NODE(),
//                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
//                GEO_OPEN_NODE(),
//                   GEO_ANIMATED_PART(LAYER_TRANSPARENT, 17, 0, 4, toad_toadle_foot_r_mesh),
//                GEO_CLOSE_NODE(),
//             GEO_CLOSE_NODE(),
//             GEO_ANIMATED_PART(LAYER_TRANSPARENT, 110, 15, -55, NULL),
//             GEO_OPEN_NODE(),
//                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
//                GEO_OPEN_NODE(),
// #ifdef VERSION_JP
//                   GEO_ANIMATED_PART(LAYER_TRANSPARENT, 17, 0, -4, toad_seg6_dl_06008520),
// #else
//                   GEO_ANIMATED_PART(LAYER_TRANSPARENT, 17, 0, -4, toad_toadle_foot_l_mesh),
// #endif
//                GEO_CLOSE_NODE(),
//             GEO_CLOSE_NODE(),
//          GEO_CLOSE_NODE(),
//       GEO_CLOSE_NODE(),
//    GEO_CLOSE_NODE(),
   GEO_RETURN(),
};

// 0x0D0003E4
const GeoLayout toad_geo[] = {
   GEO_SCALE(0x00, 22384),
   GEO_OPEN_NODE(),
      GEO_SHADOW(SHADOW_CIRCLE_9_VERTS, 0x96, 100),
      GEO_OPEN_NODE(),
         GEO_TRANSLATE_ROTATE(1, 0, 0, 0, 0, -23, 0),
         GEO_OPEN_NODE(),
            GEO_ASM(10, geo_update_layer_transparency),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
               GEO_BRANCH(1, toad_geo_000114),
               GEO_BRANCH(1, toad_geo_000114),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

UNUSED static const u64 toad_unused_1 = 0;
