#include "src/game/envfx_snow.h"

const GeoLayout toadle_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(2128),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 150, 100),
			GEO_OPEN_NODE(),
				GEO_SCALE(0, 16384),
				GEO_OPEN_NODE(),
					GEO_ASM(10, geo_update_layer_transparency),
					GEO_SWITCH_CASE(2, geo_switch_anim_state),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 83, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 126, -37, 0, toadle_toadle_head_mesh),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 4, 7, 38, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 37, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 9, -25, 3, toadle_toadle_foot_l_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 4, 7, -38, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 37, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 9, -25, -3, toadle_toadle_foot_r_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 61, -3, 52, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 17, 0, 4, toadle_toadle_arm_l_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 61, -3, -52, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 17, 0, -4, toadle_toadle_arm_r_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 34, 8, 0, toadle_toadle_body_mesh),
										GEO_ANIMATED_PART(1, 25, 8, 0, toadle_toadle_vest_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, toadle_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, toadle_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, toadle_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, toadle_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, toadle_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, toadle_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, toadle_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, toadle_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
