extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern Lights1 castle_grounds_dl_rockMat_v2_lights;
extern Lights1 castle_grounds_dl_altRockMat_v2_lights;
extern Lights1 castle_grounds_dl_toToadCaveMat_v2_lights;
extern Lights1 castle_grounds_dl_lakeBottom_v2_lights;
extern Lights1 castle_grounds_dl_grassMat_v2_lights;
extern Lights1 castle_grounds_dl_headMat_v2_lights;
extern Lights1 castle_grounds_dl_headWaterMat_v2_lights;
extern Lights1 castle_grounds_dl_headWaterFallMat_v2_lights;
extern Lights1 castle_grounds_dl_lakeWaterMat_v2_lights;
extern Lights1 castle_grounds_dl_pondWaterMat_v2_lights;
extern Lights1 castle_grounds_dl_treeMat_v2_lights;
extern Lights1 castle_grounds_dl_treeTopMat_v2_lights;
extern Lights1 castle_grounds_dl_treesTopsMat_v2_lights;
extern Lights1 castle_grounds_dl_grassBorderMat_v2_lights;
extern Lights1 castle_grounds_dl_vines_001_lights;
extern Lights1 castle_grounds_dl_vines_002_lights;
extern const MacroObject castle_grounds_area_1_Area_macro_objs[];
extern Vtx castle_grounds_dl_decorGeo_mesh_vtx_0[58];
extern Gfx castle_grounds_dl_decorGeo_mesh_tri_0[];
extern Vtx castle_grounds_dl_levelGeo_mesh_vtx_0[540];
extern Gfx castle_grounds_dl_levelGeo_mesh_tri_0[];
extern Vtx castle_grounds_dl_levelGeo_mesh_vtx_1[293];
extern Gfx castle_grounds_dl_levelGeo_mesh_tri_1[];
extern Vtx castle_grounds_dl_levelGeo_mesh_vtx_2[38];
extern Gfx castle_grounds_dl_levelGeo_mesh_tri_2[];
extern Vtx castle_grounds_dl_levelGeo_mesh_vtx_3[366];
extern Gfx castle_grounds_dl_levelGeo_mesh_tri_3[];
extern Vtx castle_grounds_dl_levelGeo_mesh_vtx_4[154];
extern Gfx castle_grounds_dl_levelGeo_mesh_tri_4[];
extern Vtx castle_grounds_dl_Head_mesh_vtx_0[213];
extern Gfx castle_grounds_dl_Head_mesh_tri_0[];
extern Vtx castle_grounds_dl_headWater_mesh_vtx_0[28];
extern Gfx castle_grounds_dl_headWater_mesh_tri_0[];
extern Vtx castle_grounds_dl_headWaterFall_mesh_vtx_0[12];
extern Gfx castle_grounds_dl_headWaterFall_mesh_tri_0[];
extern Vtx castle_grounds_dl_lakeWater_mesh_vtx_0[136];
extern Gfx castle_grounds_dl_lakeWater_mesh_tri_0[];
extern Vtx castle_grounds_dl_lakeWater_mesh_vtx_1[5];
extern Gfx castle_grounds_dl_lakeWater_mesh_tri_1[];
extern Vtx castle_grounds_dl_treeLines_mesh_vtx_0[76];
extern Gfx castle_grounds_dl_treeLines_mesh_tri_0[];
extern Vtx castle_grounds_dl_treeLines_mesh_vtx_1[88];
extern Gfx castle_grounds_dl_treeLines_mesh_tri_1[];
extern Vtx castle_grounds_dl_treeLines_mesh_vtx_2[55];
extern Gfx castle_grounds_dl_treeLines_mesh_tri_2[];
extern Vtx castle_grounds_dl_treeLines_mesh_vtx_3[26];
extern Gfx castle_grounds_dl_treeLines_mesh_tri_3[];
extern Vtx castle_grounds_dl_treeLines_mesh_vtx_4[74];
extern Gfx castle_grounds_dl_treeLines_mesh_tri_4[];
extern Vtx castle_grounds_dl_vines_mesh_vtx_0[15];
extern Gfx castle_grounds_dl_vines_mesh_tri_0[];
extern Vtx castle_grounds_dl_vines_mesh_vtx_1[21];
extern Gfx castle_grounds_dl_vines_mesh_tri_1[];

extern Gfx castle_grounds_dl_decorGeo_mesh[];
extern Gfx castle_grounds_dl_levelGeo_mesh[];
extern Gfx castle_grounds_dl_Head_mesh[];
extern Gfx castle_grounds_dl_headWater_mesh[];
extern Gfx castle_grounds_dl_headWaterFall_mesh[];
extern Gfx castle_grounds_dl_lakeWater_mesh[];
extern Gfx castle_grounds_dl_treeLines_mesh[];
extern Gfx castle_grounds_dl_vines_mesh[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];

