#include "anim_marioSwimSpinStart.inc.c"
#include "anim_marioSwimSpin.inc.c"
#include "anim_marioSwimSpinEnd.inc.c"
#include "anim_mario_air_spin_start.inc.c"
#include "anim_mario_air_spin.inc.c"
#include "anim_mario_air_spin_end.inc.c"
