extern const GeoLayout bitdw_area_1_geo[];
extern const GeoLayout bitdw_area_1[];
extern const Collision bitdw_area_1_collision[];
extern const MacroObject bitdw_area_1_area_macro_objs[];
extern Vtx bitdw_dl_world_mesh_vtx_0[584];
extern Gfx bitdw_dl_world_mesh_tri_0[];
extern Vtx bitdw_dl_world_mesh_vtx_1[244];
extern Gfx bitdw_dl_world_mesh_tri_1[];
extern Vtx bitdw_dl_world_mesh_vtx_2[5];
extern Gfx bitdw_dl_world_mesh_tri_2[];
extern Vtx bitdw_dl_Fog_mesh_vtx_0[14];
extern Gfx bitdw_dl_Fog_mesh_tri_0[];
extern Vtx bitdw_dl_dock_mesh_vtx_0[84];
extern Gfx bitdw_dl_dock_mesh_tri_0[];
extern Vtx bitdw_dl_island_mesh_vtx_0[17];
extern Gfx bitdw_dl_island_mesh_tri_0[];
extern Vtx bitdw_dl_moss_mesh_vtx_0[5];
extern Gfx bitdw_dl_moss_mesh_tri_0[];
extern Vtx bitdw_dl_moss_mesh_vtx_1[37];
extern Gfx bitdw_dl_moss_mesh_tri_1[];
extern Vtx bitdw_dl_moss_mesh_vtx_2[4];
extern Gfx bitdw_dl_moss_mesh_tri_2[];
extern Vtx bitdw_dl_water_mesh_vtx_0[12];
extern Gfx bitdw_dl_water_mesh_tri_0[];
extern Vtx bitdw_dl_water_001_mesh_vtx_0[6];
extern Gfx bitdw_dl_water_001_mesh_tri_0[];
extern Vtx bitdw_dl_waterfall_mesh_vtx_0[24];
extern Gfx bitdw_dl_waterfall_mesh_tri_0[];
extern Vtx bitdw_dl_waterfallBottom_mesh_vtx_0[5];
extern Gfx bitdw_dl_waterfallBottom_mesh_tri_0[];

extern Gfx bitdw_dl_world_mesh[];
extern Gfx bitdw_dl_Fog_mesh[];
extern Gfx bitdw_dl_dock_mesh[];
extern Gfx bitdw_dl_island_mesh[];
extern Gfx bitdw_dl_moss_mesh[];
extern Gfx bitdw_dl_water_mesh[];
extern Gfx bitdw_dl_water_001_mesh[];
extern Gfx bitdw_dl_waterfall_mesh[];
extern Gfx bitdw_dl_waterfallBottom_mesh[];
extern Gfx bitdw_dl_material_revert_render_settings[];

