#include "src/game/envfx_snow.h"

const GeoLayout sloth_switch_eyes_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 34, 0, sloth_sloth_head_mesh_mat_override_face_2___Closed_Eyes_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sloth_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 135),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 32768),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 10, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 126, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(1, 0, 0, -179, -90, 0, -180),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(1, 0, 179, 0, 0, 90, 90),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_body_mesh),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(1, sloth_sloth_chest_skinned),
											GEO_TRANSLATE_ROTATE(1, 0, 34, 0, 0, 180, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_chest_mesh),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, sloth_sloth_shoulders_skinned),
													GEO_TRANSLATE_ROTATE(1, 0, 103, 0, 0, -90, 0),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_shoulders_mesh),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(1, sloth_sloth_head_skinned),
															GEO_ROTATE(1, 0, -90, 0),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(2, geo_switch_anim_state),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(1, 0, 34, 0, sloth_sloth_head_mesh),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, sloth_switch_eyes_opt1),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_DISPLAY_LIST(1, sloth_sloth_shoulder_l_skinned),
															GEO_TRANSLATE_ROTATE(1, 102, 25, -11, -90, 0, -90),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_shoulder_l_mesh),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(1, sloth_sloth_arm_l_skinned),
																	GEO_TRANSLATE_ROTATE(1, 0, 73, 0, -1, 0, 2),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_arm_l_mesh),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(1, sloth_sloth_hand_l_skinned),
																			GEO_TRANSLATE_ROTATE(1, 0, 112, 0, -7, 1, -2),
																			GEO_OPEN_NODE(),
																				GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_hand_l_mesh),
																				GEO_OPEN_NODE(),
																					GEO_DISPLAY_LIST(1, sloth_sloth_claw_l_1_skinned),
																					GEO_TRANSLATE_ROTATE(1, 8, 41, -1, -22, 5, 10),
																					GEO_OPEN_NODE(),
																						GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_claw_l_1_mesh),
																					GEO_CLOSE_NODE(),
																					GEO_DISPLAY_LIST(1, sloth_sloth_claw_l_2_skinned),
																					GEO_TRANSLATE_ROTATE(1, -8, 42, -2, -18, 3, -4),
																					GEO_OPEN_NODE(),
																						GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_claw_l_2_mesh),
																					GEO_CLOSE_NODE(),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_DISPLAY_LIST(1, sloth_sloth_shoulder_r_skinned),
															GEO_TRANSLATE_ROTATE(1, -106, 25, -11, -180, 0, 90),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_shoulder_r_mesh),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(1, sloth_sloth_arm_r_skinned),
																	GEO_ANIMATED_PART(1, 0, 73, 0, sloth_sloth_arm_r_mesh),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(1, sloth_sloth_hand_r_skinned),
																		GEO_TRANSLATE_ROTATE(1, 0, 112, 0, 2, 0, -2),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_hand_r_mesh),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_DISPLAY_LIST(1, sloth_sloth_thigh_l_skinned),
											GEO_TRANSLATE_ROTATE(1, 0, 6, -42, -180, 0, 5),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_thigh_l_mesh),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, sloth_sloth_leg_l_skinned),
													GEO_TRANSLATE_ROTATE(1, 0, 68, 0, -3, -30, -4),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_leg_l_mesh),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(1, sloth_sloth_foot_l_skinned),
															GEO_TRANSLATE_ROTATE(1, 0, 54, 0, 0, -150, 71),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_foot_l_mesh),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_DISPLAY_LIST(1, sloth_sloth_thigh_r_skinned),
											GEO_TRANSLATE_ROTATE(1, 0, 6, 46, -180, 0, 5),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_thigh_r_mesh),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, sloth_sloth_leg_r_skinned),
													GEO_TRANSLATE_ROTATE(1, 0, 68, 0, -3, -30, -4),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_leg_r_mesh),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(1, sloth_sloth_foot_r_skinned),
															GEO_TRANSLATE_ROTATE(1, 0, 54, 0, 0, -150, 71),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(1, 0, 0, 0, sloth_sloth_foot_r_mesh),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, sloth_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, sloth_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, sloth_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, sloth_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, sloth_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, sloth_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, sloth_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, sloth_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
