extern const GeoLayout castle_inside_area_1_geo[];
extern const GeoLayout castle_inside_area_1[];
extern const Collision castle_inside_area_1_collision[];
extern const MacroObject castle_inside_area_1_macro_objs[];
extern Lights1 castle_inside_dl_sm64_material_lights;
extern Lights1 castle_inside_dl_treewall_layer1_area1_lights;
extern u8 castle_inside_dl_Leaves_3_i8[];
extern u8 castle_inside_dl_faraway_trees_ci8[];
extern u8 castle_inside_dl_faraway_trees_ci8_pal_rgba16[];
extern Vtx castle_inside_dl_Ground_mesh_vtx_cull[8];
extern Vtx castle_inside_dl_Ground_mesh_vtx_0[9];
extern Gfx castle_inside_dl_Ground_mesh_tri_0[];
extern Vtx castle_inside_dl_Ground_mesh_vtx_1[32];
extern Gfx castle_inside_dl_Ground_mesh_tri_1[];
extern Gfx mat_castle_inside_dl_sm64_material[];
extern Gfx mat_revert_castle_inside_dl_sm64_material[];
extern Gfx mat_castle_inside_dl_treewall_layer1_area1[];
extern Gfx mat_revert_castle_inside_dl_treewall_layer1_area1[];
extern Gfx castle_inside_dl_Ground_mesh[];
extern Gfx castle_inside_dl_material_revert_render_settings[];
