extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern Vtx pss_dl_Cube_mesh_vtx_0[17];
extern Gfx pss_dl_Cube_mesh_tri_0[];
extern Vtx pss_dl_Cube_mesh_vtx_1[8];
extern Gfx pss_dl_Cube_mesh_tri_1[];
extern Vtx pss_dl_Cube_001_mesh_vtx_0[87];
extern Gfx pss_dl_Cube_001_mesh_tri_0[];
extern Vtx pss_dl_SubTopWindow_mesh_vtx_0[8];
extern Gfx pss_dl_SubTopWindow_mesh_tri_0[];
extern Vtx pss_dl_Submarine_mesh_vtx_0[290];
extern Gfx pss_dl_Submarine_mesh_tri_0[];
extern Vtx pss_dl_SubmarineWater_mesh_vtx_0[4];
extern Gfx pss_dl_SubmarineWater_mesh_tri_0[];
extern Vtx pss_dl_SubmarineWater_mesh_vtx_1[12];
extern Gfx pss_dl_SubmarineWater_mesh_tri_1[];
extern Vtx pss_dl_SubmarineWindows_mesh_vtx_0[8];
extern Gfx pss_dl_SubmarineWindows_mesh_tri_0[];
extern Vtx pss_dl_levelwrapper_mesh_vtx_0[117];
extern Gfx pss_dl_levelwrapper_mesh_tri_0[];

extern Gfx pss_dl_Cube_mesh[];
extern Gfx pss_dl_Cube_001_mesh[];
extern Gfx pss_dl_SubTopWindow_mesh[];
extern Gfx pss_dl_Submarine_mesh[];
extern Gfx pss_dl_SubmarineWater_mesh[];
extern Gfx pss_dl_SubmarineWindows_mesh[];
extern Gfx pss_dl_levelwrapper_mesh[];
extern Gfx pss_dl_material_revert_render_settings[];

