#include "src/game/envfx_snow.h"

const GeoLayout bitdw_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_world_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -4943, 1996, -937, bitdw_dl_Fog_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_dock_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_island_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_moss_mesh),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bitdw_dl_water_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -4582, 1149, -809, bitdw_dl_water_001_mesh),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bitdw_dl_waterfall_mesh),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bitdw_dl_waterfallBottom_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bitdw_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -213, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bitdw_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bitdw_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
