extern const GeoLayout bitfs_area_1_geo[];
extern const GeoLayout bitfs_area_1[];
extern const Collision bitfs_area_1_collision[];
extern const MacroObject bitfs_area_1_macro_objs[];
extern Vtx bitfs_dl_SlothGeo_mesh_vtx_0[16];
extern Gfx bitfs_dl_SlothGeo_mesh_tri_0[];
extern Vtx bitfs_dl_SlothGeo_mesh_vtx_1[32];
extern Gfx bitfs_dl_SlothGeo_mesh_tri_1[];
extern Vtx bitfs_dl_SlothGeo_mesh_vtx_2[91];
extern Gfx bitfs_dl_SlothGeo_mesh_tri_2[];
extern Vtx bitfs_dl_slothriver_mesh_vtx_0[17];
extern Gfx bitfs_dl_slothriver_mesh_tri_0[];
extern Vtx bitfs_dl_TreeA_mesh_vtx_0[425];
extern Gfx bitfs_dl_TreeA_mesh_tri_0[];
extern Vtx bitfs_dl_TreeA_001_mesh_vtx_0[446];
extern Gfx bitfs_dl_TreeA_001_mesh_tri_0[];
extern Vtx bitfs_dl_TreeC_mesh_vtx_0[503];
extern Gfx bitfs_dl_TreeC_mesh_tri_0[];
extern Vtx bitfs_dl_WarpFloor_mesh_vtx_0[25];
extern Gfx bitfs_dl_WarpFloor_mesh_tri_0[];
extern Vtx bitfs_dl_house1_mesh_vtx_0[50];
extern Gfx bitfs_dl_house1_mesh_tri_0[];
extern Vtx bitfs_dl_house1foilage_mesh_vtx_0[14];
extern Gfx bitfs_dl_house1foilage_mesh_tri_0[];
extern Vtx bitfs_dl_house1foilage_001_mesh_vtx_0[14];
extern Gfx bitfs_dl_house1foilage_001_mesh_tri_0[];

extern Gfx bitfs_dl_SlothGeo_mesh[];
extern Gfx bitfs_dl_slothriver_mesh[];
extern Gfx bitfs_dl_TreeA_mesh[];
extern Gfx bitfs_dl_TreeA_001_mesh[];
extern Gfx bitfs_dl_TreeC_mesh[];
extern Gfx bitfs_dl_WarpFloor_mesh[];
extern Gfx bitfs_dl_house1_mesh[];
extern Gfx bitfs_dl_house1foilage_mesh[];
extern Gfx bitfs_dl_house1foilage_001_mesh[];
extern Gfx bitfs_dl_material_revert_render_settings[];

