extern const GeoLayout jellycube_geo[];
extern Vtx jellycube_bottom_mesh_vtx_0[14];
extern Gfx jellycube_bottom_mesh_tri_0[];
extern Vtx jellycube_midbottom_mesh_vtx_0[18];
extern Gfx jellycube_midbottom_mesh_tri_0[];
extern Vtx jellycube_midbottom_skinned_vtx_0[13];
extern Gfx jellycube_midbottom_skinned_tri_0[];
extern Vtx jellycube_midtop_mesh_vtx_0[18];
extern Gfx jellycube_midtop_mesh_tri_0[];
extern Vtx jellycube_midtop_skinned_vtx_0[13];
extern Gfx jellycube_midtop_skinned_tri_0[];
extern Vtx jellycube_top_mesh_vtx_0[18];
extern Gfx jellycube_top_mesh_tri_0[];
extern Vtx jellycube_top_mesh_vtx_1[30];
extern Gfx jellycube_top_mesh_tri_1[];
extern Vtx jellycube_top_skinned_vtx_0[13];
extern Gfx jellycube_top_skinned_tri_0[];
extern Vtx jellycube_bubs_mesh_vtx_0[28];
extern Gfx jellycube_bubs_mesh_tri_0[];

extern Gfx jellycube_bottom_mesh[];
extern Gfx jellycube_midbottom_mesh[];
extern Gfx jellycube_midbottom_skinned[];
extern Gfx jellycube_midtop_mesh[];
extern Gfx jellycube_midtop_skinned[];
extern Gfx jellycube_top_mesh[];
extern Gfx jellycube_top_skinned[];
extern Gfx jellycube_bubs_mesh[];
extern Gfx jellycube_material_revert_render_settings[];

