#include "src/game/envfx_snow.h"

const GeoLayout fruit_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 135, 65),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 98304),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -25, 0, 0, 90, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_update_layer_transparency),
							GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_egg_mesh),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 1, -355, 90, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 360, 5, 14, 53, -165),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 31, 0, -8, 162, 16),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, -1, -10, 8),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_001_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 349, 5, 14, 136, -15),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_001_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_001_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 31, 0, 2, 144, -18),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_001_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_001_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, 2, 0, -8),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_001_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_002_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 354, 7, 100, 0, -100),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_002_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_002_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, -1, 177, -8),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_002_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_002_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, 3, 15, -7),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_002_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_003_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 5, 356, 7, 80, 0, 100),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_003_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_003_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, 1, 177, 8),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_003_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_003_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, -3, 15, 7),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_003_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_004_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -1, 349, 17, 1, -103, 11),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_004_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_004_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, -4, -153, 9),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_004_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_004_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, -5, 14, 9),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_004_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_005_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -1, 360, 17, 2, -86, 168),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_005_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_005_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, -1, -170, -11),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_005_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_005_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, 4, 23, -8),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_005_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_006_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 5, 356, 18, -73, -11, 95),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_006_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_006_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, -2, -163, -5),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_006_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_006_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, 6, 40, -7),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_006_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_007_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 354, 18, -107, 11, -95),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_007_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_007_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, 2, -163, 5),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_007_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_007_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, -6, 40, 7),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_007_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_008_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -4, 358, 9, -139, -59, -23),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_008_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_008_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, 2, -159, -4),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_008_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_008_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, -4, 48, 2),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_008_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_009_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 4, 351, 9, -40, 60, 20),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_009_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_009_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 34, 0, 3, -159, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_009_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_009_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 25, 0, 1, 48, -2),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_009_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_010_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 3, 359, 8, -139, 108, -16),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_010_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_010_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, -2, -162, -4),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_010_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_010_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, 3, 31, -1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_010_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_inner_011_skinned),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -4, 352, 8, -41, -120, 25),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_inner_011_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_mid_011_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, -2, -145, 2),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_mid_011_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_petal_1_tip_011_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, -2, 23, 2),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_CONTROLLED, 0, 0, 0, fruit_petal_1_tip_011_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_CONTROLLED, fruit_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
